apiVersion: apps/v1
kind: Daemonset
metadata:
  name: my-daemon
spec
  selector:
    matchLabels:
      app:nginx
  template:
    metadata:
      labels:
        app:nginx
    spec:
      containers:
      - name: my_pod
        image: nginx:latest
        ports:
        - containerPort: 80