apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: mydaemon
  selector:
    matchLabels:
      app: mynginx
  template:
    metadata:
      labels:
        app: mynginx
    spec:
      containers:
      - name: mypod
        image: nginx:latest
        ports:
        - containerPort: 80
