apiVersion: apps/v1
kind: Pod
metadata:
    name: deployment
spec:
    replicas: 10
    selector:
        matchLabels:
           app:nginx
    template:
        metadata:
          labels:
           app:nginx
        spec:
          containers:
           - name: my_img
             image: nginx:latest
             ports:
              - containerPort: 80      
