apiVersion: apps/v1
kind: Deployment
metadata:
  name: my_deploymentpp
spec:
  replicas: 10
  selector:
    matchLabels:
      app:nginx
  template:
    metadata:
      labels:
        app:nginx
    spec:
      containers:
      - name: my_pod
        image: nginx:latest
        ports:
        - containerPort: 80