apiVersion: v1
kind: Service
metadata:
    name: my-nip
spec:
    type: NodePort
    selector:
        app: nginx
    ports:
    - name: http
      port: 32007
      targetPort: 8090
      nodePort: 30006