apiVersion: v1
kind: Deployment
metadata:
    name: my-deployment
spec:
    replicas: {{ .Values.myReplicas }}
    selector:
      app: nginx
    template:
      metadata:
        labels:
          app: nginx
      spec:
        containers:
        - name: my-co
          image: nginx:latest
          ports:
          - containerPort: 80