apiVersion: v1
kind: Pod
metadata:
    name: nginx
spec:
    initContainers:
      - name: busybox
        image: busybox
        command: ["/bin/sh"]
        args: ["-c", "sleep 50"]
    containers:
      - name: my-img1
        image: nginx:latest
        ports:
         - containerPort: 80

