apiVersion: v1
kind: Service
metadata:
    name: my-nodeip
spec:
    type: NodePort
    selector:
        app: nginx
    ports:
      - name: http
        port: 32000
        nodePort: 30006
        targetPort: 8080
    