apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
    name: my-sa-rolebinding
    namespace: default
subjects:
- kind: ServiceAccount
  name: my-sa
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: my-sa-role